/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * BS Calendar
 * Calendar aggregator for IITM BS Degree
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { api } from "../axios";
import type { ErrorType } from "../axios";
export interface Course {
  id: number;
  name: string;
  google_calendar_link: string;
  is_synced: boolean;
}

export type EventDescription = string | null;

export type EventEndAt = string | null;

export interface Event {
  id: string;
  title: string;
  description: EventDescription;
  calendar_id: number;
  start_at: string;
  end_at: EventEndAt;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type GetEventsEventsGetParams = {
  cid: number[];
  start_at: string;
  end_at: string;
};

export type ExportCalendarExportIcsGetParams = {
  cid: number[];
  name?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get Courses
 */
export const getCoursesCoursesGet = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<Course[]>({ url: `/courses`, method: "GET", signal }, options);
};

export const getGetCoursesCoursesGetQueryKey = () => {
  return [`/courses`] as const;
};

export const getGetCoursesCoursesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoursesCoursesGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCoursesCoursesGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCoursesCoursesGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCoursesCoursesGet>>
  > = ({ signal }) => getCoursesCoursesGet(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoursesCoursesGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoursesCoursesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoursesCoursesGet>>
>;
export type GetCoursesCoursesGetQueryError = ErrorType<unknown>;

export function useGetCoursesCoursesGet<
  TData = Awaited<ReturnType<typeof getCoursesCoursesGet>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoursesCoursesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoursesCoursesGet>>,
          TError,
          Awaited<ReturnType<typeof getCoursesCoursesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoursesCoursesGet<
  TData = Awaited<ReturnType<typeof getCoursesCoursesGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoursesCoursesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoursesCoursesGet>>,
          TError,
          Awaited<ReturnType<typeof getCoursesCoursesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoursesCoursesGet<
  TData = Awaited<ReturnType<typeof getCoursesCoursesGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoursesCoursesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Courses
 */

export function useGetCoursesCoursesGet<
  TData = Awaited<ReturnType<typeof getCoursesCoursesGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoursesCoursesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoursesCoursesGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Events
 */
export const getEventsEventsGet = (
  params: GetEventsEventsGetParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<Event[]>(
    { url: `/events`, method: "GET", params, signal },
    options,
  );
};

export const getGetEventsEventsGetQueryKey = (
  params?: GetEventsEventsGetParams,
) => {
  return [`/events`, ...(params ? [params] : [])] as const;
};

export const getGetEventsEventsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getEventsEventsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetEventsEventsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEventsEventsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetEventsEventsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getEventsEventsGet>>
  > = ({ signal }) => getEventsEventsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEventsEventsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEventsEventsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEventsEventsGet>>
>;
export type GetEventsEventsGetQueryError = ErrorType<HTTPValidationError>;

export function useGetEventsEventsGet<
  TData = Awaited<ReturnType<typeof getEventsEventsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetEventsEventsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEventsEventsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventsEventsGet>>,
          TError,
          Awaited<ReturnType<typeof getEventsEventsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEventsEventsGet<
  TData = Awaited<ReturnType<typeof getEventsEventsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetEventsEventsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEventsEventsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventsEventsGet>>,
          TError,
          Awaited<ReturnType<typeof getEventsEventsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEventsEventsGet<
  TData = Awaited<ReturnType<typeof getEventsEventsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetEventsEventsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEventsEventsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Events
 */

export function useGetEventsEventsGet<
  TData = Awaited<ReturnType<typeof getEventsEventsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetEventsEventsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEventsEventsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetEventsEventsGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Export Calendar
 */
export const exportCalendarExportIcsGet = (
  params: ExportCalendarExportIcsGetParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<void>(
    { url: `/export.ics`, method: "GET", params, signal },
    options,
  );
};

export const getExportCalendarExportIcsGetQueryKey = (
  params?: ExportCalendarExportIcsGetParams,
) => {
  return [`/export.ics`, ...(params ? [params] : [])] as const;
};

export const getExportCalendarExportIcsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ExportCalendarExportIcsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getExportCalendarExportIcsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof exportCalendarExportIcsGet>>
  > = ({ signal }) =>
    exportCalendarExportIcsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExportCalendarExportIcsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof exportCalendarExportIcsGet>>
>;
export type ExportCalendarExportIcsGetQueryError =
  ErrorType<HTTPValidationError>;

export function useExportCalendarExportIcsGet<
  TData = Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ExportCalendarExportIcsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
          TError,
          Awaited<ReturnType<typeof exportCalendarExportIcsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportCalendarExportIcsGet<
  TData = Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ExportCalendarExportIcsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
          TError,
          Awaited<ReturnType<typeof exportCalendarExportIcsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportCalendarExportIcsGet<
  TData = Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ExportCalendarExportIcsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Export Calendar
 */

export function useExportCalendarExportIcsGet<
  TData = Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ExportCalendarExportIcsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportCalendarExportIcsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExportCalendarExportIcsGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
