/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * BS Calendar
 * Calendar aggregator for IITM BS Degree
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { api } from "../axios";
import type { ErrorType } from "../axios";
export type CourseLastSyncAt = string | null;

export interface Course {
  id: string;
  name: string;
  level: string;
  calendar_available: boolean;
  last_sync_at: CourseLastSyncAt;
}

export type EventDescription = string | null;

export type EventEndAt = string | null;

export interface Event {
  id: string;
  title: string;
  description: EventDescription;
  calendar_id: string;
  start_at: string;
  end_at: EventEndAt;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type GetEventsApiEventsGetParams = {
  cid: string[];
  start_at: string;
  end_at: string;
};

export type ExportCalendarApiExportIcsGetParams = {
  cid: string[];
  name?: string;
};

export type GoogleAuthRedirectApiAuthRedirectGetParams = {
  code: string;
  state?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get Courses
 */
export const getCoursesApiCoursesGet = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<Course[]>({ url: `/api/courses`, method: "GET", signal }, options);
};

export const getGetCoursesApiCoursesGetQueryKey = () => {
  return [`/api/courses`] as const;
};

export const getGetCoursesApiCoursesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCoursesApiCoursesGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCoursesApiCoursesGet>>
  > = ({ signal }) => getCoursesApiCoursesGet(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoursesApiCoursesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoursesApiCoursesGet>>
>;
export type GetCoursesApiCoursesGetQueryError = ErrorType<unknown>;

export function useGetCoursesApiCoursesGet<
  TData = Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
          TError,
          Awaited<ReturnType<typeof getCoursesApiCoursesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoursesApiCoursesGet<
  TData = Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
          TError,
          Awaited<ReturnType<typeof getCoursesApiCoursesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoursesApiCoursesGet<
  TData = Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Courses
 */

export function useGetCoursesApiCoursesGet<
  TData = Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCoursesApiCoursesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoursesApiCoursesGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Events
 */
export const getEventsApiEventsGet = (
  params: GetEventsApiEventsGetParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<Event[]>(
    { url: `/api/events`, method: "GET", params, signal },
    options,
  );
};

export const getGetEventsApiEventsGetQueryKey = (
  params?: GetEventsApiEventsGetParams,
) => {
  return [`/api/events`, ...(params ? [params] : [])] as const;
};

export const getGetEventsApiEventsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getEventsApiEventsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetEventsApiEventsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEventsApiEventsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetEventsApiEventsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getEventsApiEventsGet>>
  > = ({ signal }) => getEventsApiEventsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEventsApiEventsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEventsApiEventsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEventsApiEventsGet>>
>;
export type GetEventsApiEventsGetQueryError = ErrorType<HTTPValidationError>;

export function useGetEventsApiEventsGet<
  TData = Awaited<ReturnType<typeof getEventsApiEventsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetEventsApiEventsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEventsApiEventsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventsApiEventsGet>>,
          TError,
          Awaited<ReturnType<typeof getEventsApiEventsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEventsApiEventsGet<
  TData = Awaited<ReturnType<typeof getEventsApiEventsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetEventsApiEventsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEventsApiEventsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventsApiEventsGet>>,
          TError,
          Awaited<ReturnType<typeof getEventsApiEventsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEventsApiEventsGet<
  TData = Awaited<ReturnType<typeof getEventsApiEventsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetEventsApiEventsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEventsApiEventsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Events
 */

export function useGetEventsApiEventsGet<
  TData = Awaited<ReturnType<typeof getEventsApiEventsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GetEventsApiEventsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getEventsApiEventsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetEventsApiEventsGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Export Calendar
 */
export const exportCalendarApiExportIcsGet = (
  params: ExportCalendarApiExportIcsGetParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<void>(
    { url: `/api/export.ics`, method: "GET", params, signal },
    options,
  );
};

export const getExportCalendarApiExportIcsGetQueryKey = (
  params?: ExportCalendarApiExportIcsGetParams,
) => {
  return [`/api/export.ics`, ...(params ? [params] : [])] as const;
};

export const getExportCalendarApiExportIcsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ExportCalendarApiExportIcsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getExportCalendarApiExportIcsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>
  > = ({ signal }) =>
    exportCalendarApiExportIcsGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExportCalendarApiExportIcsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>
>;
export type ExportCalendarApiExportIcsGetQueryError =
  ErrorType<HTTPValidationError>;

export function useExportCalendarApiExportIcsGet<
  TData = Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ExportCalendarApiExportIcsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
          TError,
          Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportCalendarApiExportIcsGet<
  TData = Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ExportCalendarApiExportIcsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
          TError,
          Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportCalendarApiExportIcsGet<
  TData = Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ExportCalendarApiExportIcsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Export Calendar
 */

export function useExportCalendarApiExportIcsGet<
  TData = Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: ExportCalendarApiExportIcsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportCalendarApiExportIcsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExportCalendarApiExportIcsGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns the URL to redirect users to for Google OAuth login
Implements PKCE flow for added security
 * @summary Google Auth Login
 */
export const googleAuthLoginApiAuthLoginGet = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<unknown>(
    { url: `/api/auth-login`, method: "GET", signal },
    options,
  );
};

export const getGoogleAuthLoginApiAuthLoginGetQueryKey = () => {
  return [`/api/auth-login`] as const;
};

export const getGoogleAuthLoginApiAuthLoginGetQueryOptions = <
  TData = Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGoogleAuthLoginApiAuthLoginGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>
  > = ({ signal }) => googleAuthLoginApiAuthLoginGet(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GoogleAuthLoginApiAuthLoginGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>
>;
export type GoogleAuthLoginApiAuthLoginGetQueryError = ErrorType<unknown>;

export function useGoogleAuthLoginApiAuthLoginGet<
  TData = Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
          TError,
          Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleAuthLoginApiAuthLoginGet<
  TData = Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
          TError,
          Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleAuthLoginApiAuthLoginGet<
  TData = Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Google Auth Login
 */

export function useGoogleAuthLoginApiAuthLoginGet<
  TData = Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof googleAuthLoginApiAuthLoginGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGoogleAuthLoginApiAuthLoginGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Handles the redirect from Google OAuth
Exchanges authorization code for tokens using PKCE
 * @summary Google Auth Redirect
 */
export const googleAuthRedirectApiAuthRedirectGet = (
  params: GoogleAuthRedirectApiAuthRedirectGetParams,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<unknown>(
    { url: `/api/auth-redirect`, method: "GET", params, signal },
    options,
  );
};

export const getGoogleAuthRedirectApiAuthRedirectGetQueryKey = (
  params?: GoogleAuthRedirectApiAuthRedirectGetParams,
) => {
  return [`/api/auth-redirect`, ...(params ? [params] : [])] as const;
};

export const getGoogleAuthRedirectApiAuthRedirectGetQueryOptions = <
  TData = Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GoogleAuthRedirectApiAuthRedirectGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGoogleAuthRedirectApiAuthRedirectGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>
  > = ({ signal }) =>
    googleAuthRedirectApiAuthRedirectGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GoogleAuthRedirectApiAuthRedirectGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>
>;
export type GoogleAuthRedirectApiAuthRedirectGetQueryError =
  ErrorType<HTTPValidationError>;

export function useGoogleAuthRedirectApiAuthRedirectGet<
  TData = Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GoogleAuthRedirectApiAuthRedirectGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
          TError,
          Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleAuthRedirectApiAuthRedirectGet<
  TData = Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GoogleAuthRedirectApiAuthRedirectGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
          TError,
          Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleAuthRedirectApiAuthRedirectGet<
  TData = Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GoogleAuthRedirectApiAuthRedirectGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Google Auth Redirect
 */

export function useGoogleAuthRedirectApiAuthRedirectGet<
  TData = Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
  TError = ErrorType<HTTPValidationError>,
>(
  params: GoogleAuthRedirectApiAuthRedirectGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof googleAuthRedirectApiAuthRedirectGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGoogleAuthRedirectApiAuthRedirectGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
