# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
from typing import Optional


@dataclasses.dataclass()
class Calendar:
    id: int
    course_id: Optional[str]
    ics_string: Optional[str]


@dataclasses.dataclass()
class Course:
    id: str
    name: Optional[str]
    calendar_url: Optional[str]
    last_sync_at: Optional[str]
    last_sync_http_status: Optional[int]
    level_id: Optional[int]


@dataclasses.dataclass()
class Level:
    id: int
    name: Optional[str]


@dataclasses.dataclass()
class User:
    id: int
    first_name: Optional[str]
    last_name: Optional[str]
    email: Optional[str]
    calendar_token: Optional[str]
    last_login_at: Optional[str]
    last_calendar_sync_at: Optional[str]


@dataclasses.dataclass()
class UserCourse:
    id: int
    user_id: Optional[int]
    course_id: Optional[str]
